/**
 * Test vectors for the native ports of the crypto.
 *
 * The iOS AutoFill extension and the Android autofill service each carry a
 * small reimplementation of the decryption in public/js/crypto.js. This makes
 * ciphertext with the real web code, and CI checks that both ports open it to
 * exactly the same plaintext. If the formats ever drift apart, that check
 * fails instead of autofill quietly finding nothing.
 *
 * Run with `npm run vectors` after changing crypto.js.
 */

import { writeFileSync } from "node:fs";
import {
  derivePasskeyKeys,
  encryptItem,
  generateVaultKey,
  randomBytes,
  toB64,
  wrapVaultKey,
} from "../public/js/crypto.js";

const secret = randomBytes(32);
const secretBase64 = toB64(secret);
const { encKey } = await derivePasskeyKeys(secret);
const vaultKey = await generateVaultKey();

const logins = [
  { id: "plain", name: "Example", username: "sam@example.com", password: "correct horse", url: "https://example.com" },
  { id: "unicode", name: "Café ☕ 日本", username: "zoë", password: "pässwörd🔑", url: "shop.example.co.uk" },
  { id: "long", name: "Long", username: "", password: "x".repeat(700), url: "https://a.example.org/login" },
  { id: "nopassword", name: "A note", username: "", password: "", url: "" },
];

const items = [];
for (const login of logins) {
  items.push({ id: login.id, data: await encryptItem(vaultKey, { ...login, notes: "n", history: [] }) });
}
// Not valid ciphertext, which both ports must skip rather than fail on.
items.push({ id: "broken", data: toB64(randomBytes(64)) });

const vectors = {
  note: "Generated by scripts/make-vectors.mjs from public/js/crypto.js. Do not edit by hand.",
  secret: secretBase64,
  wrappedKey: await wrapVaultKey(encKey, vaultKey),
  items,
  expected: logins
    .filter((login) => login.password)
    .map(({ id, name, username, password, url }) => ({ id, name, username, password, url })),
};

const out = "mobile/plugins/kalm-vault/test-vectors.json";
writeFileSync(out, JSON.stringify(vectors, null, 2) + "\n");
console.log(`wrote ${out}`);
